### ISSUE TITLE
Where the full list of supported capabilities could be found?

### ISSUE THREAD

**Issue by mykola-mokhnach** [kfrajtak/WinAppDriver#12]
Hello Karel,

I'm was trying to bind the stuff, which is present in the official WAD documentation at https://github.com/microsoft/WinAppDriver/blob/master/Docs/AuthoringTestScripts.md and the current source code. Unfortunately, I am unable to find the described capabilities, like for example `appArguments` or `appTopLevelWindow` in the source code of the current handlers, but only in the tests. Although, I could see some undocumented caps, like `mode` or `mainWindowTitle` inside https://github.com/kfrajtak/WinAppDriver/blob/master/WinAppDriver/CommandHandlers/NewSessionCommandHandler.cs

Could you please help me to find a correct place where I could look for the actual implementations? Or could it be that this source and the one used/documented by MS are different?

**Comment by kfrajtak** [comment]
The list of supported capabilities is mentioned in the readme file. 
Yes, there's a difference between capabilities supported in this project and those in MS project.
However, this can be fixed, so the MS capabilities are supported.

**Comment by mykola-mokhnach** [comment]
Thanks. I see that MS didn't actually open the original sources of their driver. Enterprise is so enterprise :(
