### ISSUE TITLE
Which windows systems are supported for this project？

### ISSUE THREAD

**Issue by yangyechi** [kfrajtak/WinAppDriver#14]
I noticed that Microsoft/WinAppDriver only supports Windows 10 (Home and Pro) and Windows Server 2016. So does this project support other systems？
In addition, why does Microsoft/WinAppDriver only support Windows 10 (Home and Pro) and Windows Server 2016? Does it not depend on Microsoft UIAutomation ? 
Please tell me, Thanks bro.

**Comment by kfrajtak** [comment]
This project relies on MS UI Automation which is a part of the Windows Accessibility API. 

The documentation mentions support for various platforms

> UI Automation is supported on the following operating systems: Windows XP, Windows Server 2003, Windows Server 2003 R2, Windows Vista, Windows 7, Windows 10, Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2, Windows Server 2016, and Windows Server 2019. 

I can't confirm it will work on those platforms since I only have Win 10 Enterprise on my machine. All the required libs are part of the project, feel free to give a try on a platform you choose.

**Comment by yangyechi** [comment]
> This project relies on MS UI Automation which is a part of the Windows Accessibility API.
> 
> The [documentation](https://docs.microsoft.com/en-us/windows/win32/winauto/entry-uiauto-win32#run-time-requirements) mentions support for various platforms
> 
> > UI Automation is supported on the following operating systems: Windows XP, Windows Server 2003, Windows Server 2003 R2, Windows Vista, Windows 7, Windows 10, Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2, Windows Server 2016, and Windows Server 2019.
> 
> I can't confirm it will work on those platforms since I only have Win 10 Enterprise on my machine. All the required libs are part of the project, feel free to give a try on a platform you choose.

OK, Thank you very much for answering my question.
