### ISSUE TITLE
Can I use the repo for WinForms App in Windows 10?

### ISSUE THREAD

**Issue by zydjohnHotmail** [kfrajtak/WinAppDriver#15]
Hello:
I found your repo., it looks good,
But I want to know if I can use the repo in a WinForms App project target .NET 5.0/6.0.
I am using Visual Studio 2022 on Windows 10 PC.
For example: if I want to launch a Chrome browser. Then use repo to connect to the running Chrome, and navigate to https://www.google.com/, then input search string in the input box, like "UI Test", then press Enter key.
If for WinForms not possible, then target .net framework is also OK.
Thanks,

**Comment by kfrajtak** [comment]
Hi,
I haven't tested it my self, but I believe the UI automation can be applied to any WinForms application no matter what .net framework was used to build it.
For testing inside browser use Selenium and ChromeDriver.

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks for your reply.  Do you have some code samples on how to use ChromeDriver?
Thanks,

**Comment by kfrajtak** [comment]
https://chromedriver.chromium.org/getting-started
