### ISSUE TITLE
Usages

### ISSUE THREAD

**Issue by VladyslavKhvorostianyi** [kfrajtak/WinAppDriver#2]
Hello @kfrajtak ,

I want to help you with developing the WinAppDriver. But I need it for testing a commercial application, 
can I do it with Salesforce license?

Can you add some usages of the driver like in [https://github.com/Microsoft/WinAppDriver](https://github.com/Microsoft/WinAppDriver),
because I didn't get how to set up a test with it?

**Comment by kfrajtak** [comment]
I have added the license. Usages will be added soon.

**Comment by kfrajtak** [comment]
The tool is under development, I am personally running it in the debug mode directly from Visual Studio. If you are familiar with Selenium concepts then you will be able to use it. Some features might not be implemented or supported. Feel free to ask or create an issue.
