### ISSUE TITLE
Unified Service Desk 4.1 for Dynamics 365 - Automation

### ISSUE THREAD

**Issue by jjbright** [kfrajtak/WinAppDriver#8]
Does this tool help automating the USD 4.1.  Its a software for Dynamics 365, with WPF, UIA components and cefsharp process of Chrome running inside.

**Comment by kfrajtak** [comment]
The tool can automate WinForms applications (I am using it to automate an app with quite complicated UI where MS WinAppDriver [failed](https://github.com/microsoft/WinAppDriver/issues/333))and have been tried with UWP apps like "Clocks & Alarms" and "Calculator", though on the basic level.

**Comment by jjbright** [comment]
This application is based on uia controls, not winforms... also it contains the browser engine to render the screens.

Close #8

**Comment by kfrajtak** [comment]
UIA controls are fine. if they can be discovered in UIAVerify tool ...

**Comment by kfrajtak** [comment]
I downloaded the app and checked the login screen using UIAVerify. I think you are safe to go. Still not sure about the CEF.

**Comment by jjbright** [comment]
Cefsharp is used from the dashboard, I know login screens are not problematic

**Comment by kfrajtak** [comment]
I don't have access to running Dynamics instance, but tried it on the sample from [here](http://opensource.spotify.com/cefbuilds/index.html#windows32_builds) and it worked.

The sample is a simple browser, I have navigated to React TodoMVC sample (http://todomvc.com/examples/react/#/) and send text to the edit element there:
```
var edit = session.FindElement(By.XPath("//Edit"));
edit.SendKeys("Edit!");
```
